use crate::graphics::vulkan::vk_structure_types;

use super::{raw, vk_pfn_types, vk_structure_types::VkStructureType};

#[repr(C)]
pub struct VkInstanceCreateInfo {
    pub s_type: VkStructureType,
    pub p_next: *const std::ffi::c_void,
    pub flags: u32,
    pub p_application_info: *const VkApplicationInfo,
    pub enabled_layer_count: u32,
    pub pp_enabled_layer_names: *const *const std::ffi::c_char,
    pub enabled_extension_count: u32,
    pub pp_enabled_extension_names: *const *const std::ffi::c_char,
}

#[repr(C)]
pub struct VkApplicationInfo {
    pub s_type: VkStructureType,
    pub p_next: *const std::ffi::c_void,
    pub p_application_name: *const i8,
    pub application_version: u32,
    pub p_engine_name: *const i8,
    pub engine_version: u32,
    pub api_version: u32,
}

#[repr(C)]
pub struct VkXlibSurfaceCreateInfoKHR {
    pub s_type: VkStructureType,
    pub p_next: *const std::ffi::c_void,
    pub flags: u32,
    pub dpy: *mut raw::XDisplay,
    pub window: raw::XWindow,
}

#[repr(C)]
#[derive(Debug)]
pub struct VkPhysicalDeviceProperties {
    pub api_version: u32,
    pub driver_version: u32,
    pub vendor_id: u32,
    pub device_id: u32,
    pub device_type: vk_structure_types::VkPhysicalDeviceType,
    pub device_name: [i8; 256_usize],
    pub pipeline_cache_uuid: [u8; 16_usize],
    pub limits: VkPhysicalDeviceLimits,
}

#[repr(C)]
#[derive(Debug, Default)]
pub struct VkPhysicalDeviceLimits {
    max_image_dimension_1d: u32,
    max_image_dimension_2d: u32,
    max_image_dimension_3d: u32,
    max_image_dimension_cube: u32,
    max_image_array_layers: u32,
    max_texel_buffer_elements: u32,
    max_uniform_buffer_range: u32,
    max_storage_buffer_range: u32,
    max_push_constants_size: u32,
    max_memory_allocation_count: u32,
    max_sampler_allocation_count: u32,
    buffer_image_granularity: raw::VkDeviceSize,
    sparse_address_space_size: raw::VkDeviceSize,
    max_bound_descriptor_sets: u32,
    max_per_stage_descriptor_samplers: u32,
    max_per_stage_descriptor_uniform_buffers: u32,
    max_per_stage_descriptor_storage_buffers: u32,
    max_per_stage_descriptor_sampled_images: u32,
    max_per_stage_descriptor_storage_images: u32,
    max_per_stage_descriptor_input_attachments: u32,
    max_per_stage_resources: u32,
    max_descriptor_set_samplers: u32,
    max_descriptor_set_uniform_buffers: u32,
    max_descriptor_set_uniform_buffers_dynamic: u32,
    max_descriptor_set_storage_buffers: u32,
    max_descriptor_set_storage_buffers_dynamic: u32,
    max_descriptor_set_sampled_images: u32,
    max_descriptor_set_storage_images: u32,
    max_descriptor_set_input_attachments: u32,
    max_vertex_input_attributes: u32,
    max_vertex_input_bindings: u32,
    max_vertex_input_attribute_offset: u32,
    max_vertex_input_binding_stride: u32,
    max_vertex_output_components: u32,
    max_tessellation_generation_level: u32,
    max_tessellation_patch_size: u32,
    max_tessellation_control_per_vertex_input_components: u32,
    max_tessellation_control_per_vertex_output_components: u32,
    max_tessellation_control_per_patch_output_components: u32,
    max_tessellation_control_total_output_components: u32,
    max_tessellation_evaluation_input_components: u32,
    max_tessellation_evaluation_output_components: u32,
    max_geometry_shader_invocations: u32,
    max_geometry_input_components: u32,
    max_geometry_output_components: u32,
    max_geometry_output_vertices: u32,
    max_geometry_total_output_components: u32,
    max_fragment_input_components: u32,
    max_fragment_output_attachments: u32,
    max_fragment_dual_src_attachments: u32,
    max_fragment_combined_output_resources: u32,
    max_compute_shared_memory_size: u32,
    max_compute_work_group_count: [u32; 3],
    max_compute_work_group_invocations: u32,
    max_compute_work_group_size: [u32; 3],
    sub_pixel_precision_bits: u32,
    sub_texel_precision_bits: u32,
    mipmap_precision_bits: u32,
    max_draw_indexed_index_value: u32,
    max_draw_indirect_count: u32,
    max_sampler_lod_bias: f32,
    max_sampler_anisotropy: f32,
    max_viewports: u32,
    max_viewport_dimensions: [u32; 2],
    viewport_bounds_range: [f32; 2],
    viewport_sub_pixel_bits: u32,
    min_memory_map_alignment: isize,
    min_texel_buffer_offset_alignment: raw::VkDeviceSize,
    min_uniform_buffer_offset_alignment: raw::VkDeviceSize,
    min_storage_buffer_offset_alignment: raw::VkDeviceSize,
    min_texel_offset: i32,
    max_texel_offset: u32,
    min_texel_gather_offset: i32,
    max_texel_gather_offset: u32,
    min_interpolation_offset: f32,
    max_interpolation_offset: f32,
    sub_pixel_interpolation_offset_bits: u32,
    max_framebuffer_width: u32,
    max_framebuffer_height: u32,
    max_framebuffer_layers: u32,
    framebuffer_color_sample_counts: raw::VkSampleCountFlags,
    framebuffer_depth_sample_counts: raw::VkSampleCountFlags,
    framebuffer_stencil_sample_counts: raw::VkSampleCountFlags,
    framebuffer_no_attachments_sample_counts: raw::VkSampleCountFlags,
    max_color_attachments: u32,
    sampled_image_color_sample_counts: raw::VkSampleCountFlags,
    sampled_image_integer_sample_counts: raw::VkSampleCountFlags,
    sampled_image_depth_sample_counts: raw::VkSampleCountFlags,
    sampled_image_stencil_sample_counts: raw::VkSampleCountFlags,
    storage_image_sample_counts: raw::VkSampleCountFlags,
    max_sample_mask_words: u32,
    timestamp_compute_and_graphics: raw::VkBool32,
    timestamp_period: f32,
    max_clip_distances: u32,
    max_cull_distances: u32,
    max_combined_clip_and_cull_distances: u32,
    discrete_queue_priorities: u32,
    point_size_range: [f32; 2],
    line_width_range: [f32; 2],
    point_size_granularity: f32,
    line_width_granularity: f32,
    strict_lines: raw::VkBool32,
    standard_sample_locations: raw::VkBool32,
    optimal_buffer_copy_offset_alignment: raw::VkDeviceSize,
    optimal_buffer_copy_row_pitch_alignment: raw::VkDeviceSize,
    non_coherent_atom_size: raw::VkDeviceSize,
}

#[derive(Debug, Clone, Copy)]
pub struct VulkanInstanceFns {
    pub create_xlib_surface: vk_pfn_types::PFNvkCreateXlibSurfaceKHR,
    pub enumerate_physical_devices: vk_pfn_types::PFNvkEnumeratePhysicalDevices,
}
