#[derive(Debug)]
pub enum Event {
    Key {
        _x: i32,
        _y: i32,
        state: u32,
        keycode: u32,
    },
    Mouse {
        x: i32,
        y: i32,
        state: u32,
        keycode: u32,
    },
    Motion {
        x: i32,
        y: i32,
    },
    EnterNotify,
    LeaveNotify,
    FocusIn,
    FocusOut,
    VisibilityNotify,
    CreateNotify,
    DestroyNotify,
    UnmapNotify,
    MapNotify,
    MapRequest,
    ReparentNotify,
    ConfigureNotify,
    GravityNotify,
    ResizeRequest {
        width: i32,
        height: i32,
    },
    PropertyNotify,
    SelectionClear,
    SelectionRequest,
    SelectionNotify,
    ColormapNotify,
    ClientMessage,
    MappingNotify,
    GenericEvent,
    LASTEvent,
    Quit,
    None,
}
